runtime: nodejs

handlers:
  - url: /
    static_files: dist/gcloud-angular/index.html
    upload: dist/gcloud-angular/index.html
  - url: /
    static_dir: dist/gcloud-angular

skip_files:
  - e2e/
  - node_modules/
  - src/
  - ^(.*/)?\..*$
  - ^(.*/)?.*\.json$
  - ^(.*/)?.*\.md$
  - ^(.*/)?.*\.yaml$
  - ^LICENSE