runtime: nodejs10

env_variables:
  CHROME_BIN: require('puppeteer').executablePath()

handlers:
  - url: /
    static_files: dist/gcloud-angular/index.html
    upload: dist/gcloud-angular/index.html
  - url: /
    static_dir: dist/gcloud-angular
